apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mikrotik-operator
  namespace: mikrotik-operator-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: mikrotik-operator
