{{- if .Values.ui.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mikrotik-operator.ui.serviceAccountName" . }}
  labels:
    {{- include "mikrotik-operator.ui.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
