apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- crd/bases/mikrotik.operator.io_mikrotikrouters.yaml
- crd/bases/mikrotik.operator.io_mikrotikroutes.yaml
- crd/bases/mikrotik.operator.io_mikrotikfirewallrules.yaml
- crd/bases/mikrotik.operator.io_mikrotikdnsrecords.yaml
- crd/bases/mikrotik.operator.io_mikrotikportforwards.yaml
- crd/bases/mikrotik.operator.io_mikrotikbackups.yaml
- crd/bases/mikrotik.operator.io_mikrotikrestores.yaml
- rbac/role.yaml
- manager/deployment.yaml
- manager/pdb.yaml
- ingressclass.yaml
